# Generated by Django 4.2.1 on 2023-06-13 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posistion", models.CharField(blank=True, max_length=250, null=True)),
                ("company", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AP", "APPLIED"),
                            ("CO", "CONTACTED"),
                            ("IV", "INTERVIEWED"),
                            ("EV", "EVALUATED"),
                            ("JP", "JOB_PROPOSISTION"),
                            ("DE", "DENIED"),
                            ("AC", "ACCEPPTED"),
                            ("RE", "REJECTED"),
                        ],
                        default="AP",
                        max_length=2,
                    ),
                ),
                ("apply_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("link", models.CharField(max_length=1000)),
                (
                    "salary",
                    models.CharField(
                        blank=True, default="Not specified", max_length=100, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
