# Generated by Django 4.2.1 on 2023-06-12 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("posistion", models.TextField(blank=True, max_length=250, null=True)),
                ("company", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AP", "APPLIED"),
                            ("CO", "CONTACTED"),
                            ("IV", "INTERVIEWED"),
                            ("EV", "EVALUATED"),
                            ("JP", "JOB_PROPOSISTION"),
                            ("DE", "DENIED"),
                            ("AC", "ACCEPPTED"),
                            ("RE", "REJECTED"),
                        ],
                        default="AP",
                        max_length=2,
                    ),
                ),
                ("apply_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("link", models.CharField(max_length=1000)),
                (
                    "salary",
                    models.CharField(
                        blank=True, default="Not specified", max_length=100, null=True
                    ),
                ),
            ],
        ),
    ]
