# Generated by Django 4.2.1 on 2023-06-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="posistion",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
