# Generated by Django 4.2.2 on 2023-06-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_joboffer_ai_generated_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("about", models.TextField(null=True)),
            ],
        ),
    ]
