# Generated by Django 4.2.2 on 2023-06-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_company_options_alter_joboffer_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="about",
            new_name="general_info",
        ),
        migrations.AddField(
            model_name="joboffer",
            name="company_personalized_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
